/**
 * Below are the colors that are used in the app. The colors are defined in the light and dark mode.
 * There are many other ways to style your app. For example, [Nativewind](https://www.nativewind.dev/), [Tamagui](https://tamagui.dev/), [unistyles](https://reactnativeunistyles.vercel.app), etc.
 */

export const interestsOptions: string[] = [
  "Anime",
  "Astrologia",
  "Fotografia",
  "Historia",
  "Kino / Filmy",
  "Koncerty",
  "Muzea",
  "Pisanie",
  "Sztuka",
  "Tatuaże",
  "Teatr",
  "Hip-hop",
  "Jazz",
  "Muzyka klasyczna",
  "Pop",
  "Rock",
  "Czytanie",
  "Dietetyka",
  "Głębokie rozmowy",
  "Nauka",
  "Psychologia",
  "Technologia",
  "Gotowanie",
  "Kawa",
  "Moda",
  "Ogrodnictwo",
  "Podróże",
  "Spacery",
  "Sushi",
  "Bieganie",
  "Joga",
  "Koszykówka",
  "Piłka nożna",
  "Pływanie",
  "Rower",
  "Siatkówka",
  "Siłownia",
  "Tenis",
  "Taniec",
  "Gry planszowe",
  "Gry wideo",
  "Nocne życie",
  "Dinozaury",
  "Koty",
  "Psy",
  "Wydry",
];

export const interestsOptionsEmoji: string[] = [
  '🎥 Anime 🎥',
  '🌟 Astrologia 🌟',
  '📸 Fotografia 📸',
  '📜 Historia 📜',
  '🎬 Kino / Filmy 🎬',
  '🎤 Koncerty 🎤',
  '🏛️ Muzea 🏛️',
  '✍️ Pisanie ✍️',
  '🎨 Sztuka 🎨',
  '💉 Tatuaże 💉',
  '🎭 Teatr 🎭',
  '🎧 Hip-hop 🎧',
  '🎷 Jazz 🎷',
  '🎻 Muzyka klasyczna 🎻',
  '🎵 Pop 🎵',
  '🎸 Rock 🎸',
  '📚 Czytanie 📚',
  '🥗 Dietetyka 🥗',
  '💭 Głębokie rozmowy 💭',
  '🔬 Nauka 🔬',
  '🧠 Psychologia 🧠',
  '💻 Technologia 💻',
  '🍳 Gotowanie 🍳',
  '☕ Kawa ☕',
  '👗 Moda 👗',
  '🌱 Ogrodnictwo 🌱',
  '✈️ Podróże ✈️',
  '🚶 Spacery 🚶',
  '🍣 Sushi 🍣',
  '🏃 Bieganie 🏃',
  '🧘 Joga 🧘',
  '🏀 Koszykówka 🏀',
  '⚽ Piłka nożna ⚽',
  '🏊 Pływanie 🏊',
  '🚴 Rower 🚴',
  '🏐 Siatkówka 🏐',
  '💪 Siłownia 💪',
  '🎾 Tenis 🎾',
  '💃 Taniec 💃',
  '🎲 Gry planszowe 🎲',
  '🎮 Gry wideo 🎮',
  '🌃 Nocne życie 🌃',
  '🦖 Dinozaury 🦖',
  '😺 Koty 😺',
  '🐶 Psy 🐶',
  '🦦 Wydry 🦦'
];